# Numpy Arrays
an alternative to Python lists

###### Advantages
1. fast
2. easy to work with
3. give users the opportunity to perform calculations across entire arrays

In [10]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)

In [11]:
type(np_height)

numpy.ndarray

## Element-wise calculations

* These operations are very **fast** and computationally **efficient**.
* They are particularly helpful when you have 1000s of observations in your data.

In [12]:
bmi = np_weight / np_height ** 2
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


## Subsetting

In [13]:
bmi > 23

array([ True,  True,  True,  True,  True,  True])

In [17]:
print(bmi[bmi > 23])

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]
